# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
# skip generating missing sql type definitions because is not supported by Enums with SQLite. See: https://github.com/adwhit/diesel-derive-enum#sqlite
generate_missing_sql_type_definitions = false

[migrations_directory]
dir = "./migrations"
